<?php
require_once 'apu.php';
varmista_kirjautuminen();
?>
<!DOCTYPE HTML>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <link rel="stylesheet" type="text/css" href="css/global.css">
        <title>Data uploader</title>
    </head>
    <body>
        <?php require_once 'apu/header.html'; ?>
        <h2>Import data</h2>
        <p>Import classification data generated by IC-PCA.</p>
        <form action="import_classes.php" method="post" enctype="multipart/form-data">
            <label for="classesfile">Classes file: </label>
            <input type="file" name="classesfile" id="classesfile">
            <input type="submit" name="submit">
        </form>
        <?php
        
        
        
        ?>
    </body>
</html>